#!/bin/bash
#SBATCH -p cca -C rome
#SBATCH -N1
#SBATCH --mail-type=ALL --mail-user=barons2@unlv.nevada.edu
#SBATCH -t 0:15:00

date
hostname
module purge
module load slurm python
echo

python ../../../scripts/midplane_pressure.py 'const_opac_diffusion_reflecting'
