#!/bin/bash
#SBATCH -p gen -C rome,ib --exclusive
#SBATCH -N1 --ntasks=16
#SBATCH --mail-type=ALL --mail-user=barons2@unlv.nevada.edu
#SBATCH -t 0:01:00

date
hostname
module purge
module load slurm openmpi hdf5/mpi
echo

mpirun $ATHENA/bin/athena.beam_gid0_rot -i athinput.beam_gid0_rot
