#!/bin/bash
#SBATCH -N1 -p gen -C rome,ib --exclusive
#SBATCH --mail-type=ALL --mail-user=barons2@unlv.nevada.edu
#SBATCH -t 1:00:00

date
hostname
mpirun $ATHENA -i athinput.beam -d output -t 0:55:00
